### PR TITLE
fixed submodule issue

### PR DESCRIPTION
**Pull request by gat786**
This pr Solves the submodule issue and cloning the repo will now result in submodules also getting cloned correctly.

### CODE REVIEW

**Comment by gat786** [comment]
solves #1

**Comment by mar-galho** [comment]
Hey @gat786 !

Thanks. However, removing the folders from the .gitignore isn't a viable option, for many reasons.

Have you tried this sequence? I'll try it in a few minutes:

```
git clone https://github.com/RicardoPrins/thisisaterminal.git
cd thisisaterminal
git submodule update --init --recursive
```

I'm thinking this works. For some reason, the --recursive flag isn't working, I need to investigate why.

**Comment by mar-galho** [comment]
I'll possibly spin a few virtual machines to avoid the "it works on my machine" issue when fixing this.

The long solution will surely work, which will be writing a script to clone both folders directly into the person's folder structure...I'll try to avoid that one, but if I can't find a decent git command to simplify the task, that will have to do it.

**Comment by mar-galho** [comment]
It turns out that the "bad" solution will have to be adopted. I'll fix the README.md file accordingly. These will have to be cloned individually until I figure out a better way of doing it.

**Pull request closed without merging**
